export const SKIP_SONG = "SKIP_SONG"
export const SONG_ENDED = "SONG_ENDED"
export const CHOOSE_SONG = "CHOOSE_SONG"
export const IS_PLAYING = "IS_PLAYING"
export const RESTORE_SONG = "LIKE_SONG"
export const DELETE_SONG = "DELETE_SONG"
export const SONG_INDEX_MINUS = "SONG_INDEX_MINUS"
export const SONG_INDEX_PLUS = "SONG_INDEX_PLUS"